create table dim_tracks(
    track_id char(22) primary key,
    track_name varchar(1000) not null,
    explicit boolean
);
create table dim_artists(
    artist_id integer generated by default as identity primary key,
    artist_name varchar(1000) not null
);
create table dim_albums(
    album_id integer generated by default as identity primary key,
    album_name varchar(1000) not null
);
create table dim_genres (
    genre_id integer generated by default as identity primary key,
    track_genre varchar(1000) not null 
);
create table fact_tracks(
    track_id char(22) references dim_tracks(track_id),
    artist_id integer references dim_artists(artist_id),
    album_id integer references dim_albums(album_id),
    genre_id integer references dim_genres(genre_id),
    fact_id integer generated by default as identity primary key,
    popularity integer,
    duration_ms integer,
    danceability float,
    energy float,
    key integer,
    loudness float,
    mode integer,
    speechiness float,
    acousticness float,
    instrumentalness float,
    liveness float,
    valence float,
    tempo float,
    time_signature integer
);